---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Network:
    - Router:
        - abbr: ISP
          href: https://192.168.8.1/      
    - Tailscale:
        - icon: si-tailscale
          href: https://login.tailscale.com/admin/machines?refreshed=true
- Domain:
    - Cloudflare:
        - icon: cloudflare.png
          href: https://dash.cloudflare.com/
    - Tunnels:
        - icon: cloudflare-zero-trust.png
          href: https://dash.cloudflare.com/0e7e5f1e680156851236235507b82f23/one/networks/connectors
- Developer:
    - Github:
        - icon: si-github
          href: https://github.com/shen-nm
- Me:
    - Portfolio:
        - abbr: SM
          href: https://shenmilan.com
    - Launch Page:
        - icon: si-linktree
          href: https://links.shenmilan.com
